In [1]:
# import the libearies
import pandas as pd
import numpy as np

In [2]:
# 1) Identify the data to be used, the type of problem to be solved and the target variable of the problem.Create a dataframe based on the datafile provided.

In [3]:
# Load the data
test=pd.read_csv(r"C:\Users\RBI\Downloads\iris_modified.csv")

In [4]:
# display the data
test.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

# Feature Handeling

In [5]:
# check the shape 
test.shape

(150, 5)

In [6]:
# check for null values 
test.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

There are no null values present in the dataset.

* This is a classification problem.
* The target varibale is Species.

In [7]:
# 2) Read the features (which are column names in the csv) where “is_selected”=True and create the X and the Y from the dataframe.

In [8]:
test.species.value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [9]:
# convert species to numerical 
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
test["species"]=le.fit_transform(test['species'])

# Feature Generation

In [10]:
# Split data into X & Y
X = test.values[:,0:-1]
Y = test.values[:,-1]

In [11]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [12]:
# 3) Split the data into training and validation sets based on the given split ratio and the random seed value.

In [13]:
# Split the data into test and train 
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8, random_state=10)

In [14]:
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [15]:
# 4) Parse the Json and identify the model where the algorithm “is_selected”=True. Identify the hyperparameters to be used to build those models.Build the selected models and perform hyperparameter tuning using GridSearchCV.

# Model Building

## 1. Random Forest

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier


In [22]:
rf=RandomForestClassifier(random_state=50)

In [23]:
param_grid = {
    'n_estimators':list(range(10,31)),
    'max_depth':list(range(20,31)),
    'min_samples_leaf':list(range(5,51)),
    'n_jobs': [None]
}


In [24]:
CV_rf = GridSearchCV(estimator=rf, param_grid=param_grid, cv=2)
CV_rf.fit(X_train,Y_train)


KeyboardInterrupt



In [ ]:
CV_rf.best_params_

#### Model building using Grid search after parsing hyperparams.

In [ ]:
model_RF=RandomForestClassifier(random_state=42, max_depth=20, min_samples_leaf=7, n_estimators=10)
model_RF.fit(X_train, Y_train)

In [ ]:
model_RF.fit(X_train, Y_train)

In [ ]:
pred=model_RF.predict(X_test)

In [ ]:
model_RF=RandomForestClassifier(random_state=100, n_estimators=10, max_depth=20,min_samples_leaf=7)

In [ ]:
model_RF.fit(X_train,Y_train)
pred=model_RF.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(Y_test,pred)
print(cfm)

print("Classification report: ")
print(classification_report(Y_test,pred))


The accuracy obtain by Random Forest is 93%.

## 2. Descision Tree Classifier

In [56]:
from sklearn.tree import DecisionTreeClassifier

In [57]:
param_grid = {'max_depth':[4,5,6,7],
              'min_samples_leaf':[12,6],
              'criterion':["entropy"],
              'splitter': ["best"]
             }
model_DT = DecisionTreeClassifier(random_state=10)
grid_search = GridSearchCV(estimator=model_DT, param_grid=param_grid, cv=5)
grid_search.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=10),
             param_grid={'criterion': ['entropy'], 'max_depth': [4, 5, 6, 7],
                         'min_samples_leaf': [12, 6], 'splitter': ['best']})

In [58]:
final_model = grid_search.best_estimator_
final_model

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=12,
                       random_state=10)

#### Model building using Grid search after parsing hyperparams.

In [59]:

model_DT = DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=12,
                       splitter='best')
model_DT.fit(X_train, Y_train)
y_pred = model_DT.predict(X_test)

In [61]:
from sklearn.metrics import confusion_matrix,classification_report
 
cfm=confusion_matrix(Y_test,y_pred)
print(cfm)

print("Classification report: ") 
print(classification_report(Y_test,y_pred))

[[10  0  0]
 [ 0 11  2]
 [ 0  0  7]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        10
         1.0       1.00      0.85      0.92        13
         2.0       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.95      0.93        30
weighted avg       0.95      0.93      0.93        30



The accuracy obtain by Descision Tree is 93%.

## 3. Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression

In [48]:

param_grid = {
    'max_iter':list(range(30,51)), 
    'C': [0.5, 0.6, 0.7, 0.8],
    'l1_ratio': [0.5, 0.6, 0.7, 0.8],  # Range of l1_ratio values
    'penalty': ['elasticnet'],  # Using elastic net penalty
    'solver': ['saga']
}

In [49]:
model_LR = LogisticRegression(random_state=10)
gs = GridSearchCV(estimator=model_LR, param_grid=param_grid, cv=5, n_jobs=2)
gs.fit(X_train,Y_train)

C:\Users\RBI\ana3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


GridSearchCV(cv=5, estimator=LogisticRegression(random_state=10), n_jobs=2,
             param_grid={'C': [0.5, 0.6, 0.7, 0.8],
                         'l1_ratio': [0.5, 0.6, 0.7, 0.8],
                         'max_iter': [30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
                                      40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
                                      50],
                         'penalty': ['elasticnet'], 'solver': ['saga']})

In [50]:
final_model = gs.best_estimator_
final_model

LogisticRegression(C=0.5, l1_ratio=0.5, max_iter=30, penalty='elasticnet',
                   random_state=10, solver='saga')

#### Model building using Grid search after parsing hyperparams.

In [52]:
# Training the model
model_DT = LogisticRegression(C=0.5, l1_ratio=0.5, max_iter=30, penalty='elasticnet',
                   random_state=10, solver='saga')
model_DT.fit(X_train, Y_train)
y_pred = model_DT.predict(X_test)

C:\Users\RBI\ana3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [53]:
from sklearn.metrics import confusion_matrix,classification_report
 
cfm=confusion_matrix(Y_test,y_pred)
print(cfm)

print("Classification report: ") 
print(classification_report(Y_test,y_pred))

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        10
         1.0       1.00      0.92      0.96        13
         2.0       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



The accuracy obtained by Random Forest is 97%.

## 4. SVM

In [64]:
from sklearn.svm import SVC

In [75]:
params = {
    'kernel':['linear','rbf','poly','sigmoid'],
    'C':[566,79],
    'gamma':['auto','scale','custom'],
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'tol':[7],
    'max_iter':[7],
}
model_svm=SVC()

In [76]:
# perfom Grid Search 
grid_search= GridSearchCV(estimator=model_svm,param_grid=params, cv=5, n_jobs=-1)
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [566, 79], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
                         'max_iter': [7], 'tol': [7]})

In [77]:
final_model = grid_search.best_estimator_
final_model

SVC(C=566, gamma=1, kernel='linear', max_iter=7, tol=7)

#### Model building using Grid search after parsing hyperparams.

In [82]:
# Training the model
model_svm=SVC(C=566, gamma=1, kernel='linear', max_iter=7, tol=7)
model_svm.fit(X_train, Y_train)
y_pred = model_svm.predict(X_test)

In [87]:
from sklearn.metrics import confusion_matrix,classification_report
cfm=confusion_matrix(Y_test,y_pred)
print(cfm)
print('Classification report:')
print(classification_report(Y_test,y_pred))

[[ 0  0 10]
 [ 0  0 13]
 [ 0  0  7]]
Classification report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        10
         1.0       0.00      0.00      0.00        13
         2.0       0.23      1.00      0.38         7

    accuracy                           0.23        30
   macro avg       0.08      0.33      0.13        30
weighted avg       0.05      0.23      0.09        30



C:\Users\RBI\ana3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RBI\ana3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RBI\ana3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


The accuracy obtained for SVM is 23%.

## 5. KNN

In [90]:
from sklearn.neighbors import KNeighborsClassifier

In [107]:
params={
    'n_neighbors':[78],
    'weights':['distance'],
     'algorithm':['auto'],
}
model_KNN= KNeighborsClassifier()

In [108]:
gs = GridSearchCV(model_KNN, param_grid=params, cv=5)
gs.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'], 'n_neighbors': [78],
                         'weights': ['distance']})

In [110]:
final_model = gs.best_estimator_
final_model

KNeighborsClassifier(n_neighbors=78, weights='distance')

#### Model building using Grid search after parsing hyperparams.

In [112]:
# Training the model
gs= KNeighborsClassifier(algorithm='auto', n_neighbors=78, weights='distance')
gs.fit(X_train, Y_train)
y_pred = gs.predict(X_test)

In [113]:
from sklearn.metrics import confusion_matrix,classification_report
 
cfm=confusion_matrix(Y_test,y_pred)
print(cfm)

print("Classification report: ") 
print(classification_report(Y_test,y_pred))

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
Classification report: 
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        10
         1.0       1.00      0.92      0.96        13
         2.0       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



The accuracy obtained for KNN is 97%.

## Conclusion 

* Random Forest  accuracy = 93%
* Decision Tree  accuracy = 93%
* Logistic Regression  accuracy = 97%
* SVM  accuracy = 23%
* KNN   accuracy = 97%

K-Nearest Neighbour and Logistic Regression give the best accuracy of 97%.